(function(){
  const countEl=document.getElementById('playerCount'), button=document.getElementById('rollDice'), board=document.getElementById('diceBoard'), summary=document.getElementById('diceSummary');
  if(!button||!board||!countEl) return;
  const pipMap={1:[5],2:[1,9],3:[1,5,9],4:[1,3,7,9],5:[1,3,5,7,9],6:[1,3,4,6,7,9]};
  const rand=()=>Math.floor(Math.random()*6)+1;
  const pips=n=>pipMap[n].map(pos=>`<span class="pip pip-${pos}"></span>`).join('');
  function cubeMarkup(){return `<div class="die-cube"><div class="die-face die-front">${pips(1)}</div><div class="die-face die-back">${pips(6)}</div><div class="die-face die-right">${pips(3)}</div><div class="die-face die-left">${pips(4)}</div><div class="die-face die-top">${pips(5)}</div><div class="die-face die-bottom">${pips(2)}</div></div>`;}
  const finalRotation={1:'rotateX(0deg) rotateY(0deg) rotateZ(0deg)',2:'rotateX(-90deg) rotateY(0deg) rotateZ(0deg)',3:'rotateX(0deg) rotateY(-90deg) rotateZ(0deg)',4:'rotateX(0deg) rotateY(90deg) rotateZ(0deg)',5:'rotateX(90deg) rotateY(0deg) rotateZ(0deg)',6:'rotateX(0deg) rotateY(180deg) rotateZ(0deg)'};
  function renderBoard(count){board.innerHTML=''; for(let i=1;i<=count;i++){const card=document.createElement('article'); card.className='dice-player-card'; card.innerHTML=`<div class="player-name">플레이어 ${i}</div><div class="dice-stage"><div class="dice-cube-wrap">${cubeMarkup()}</div></div><div class="dice-result-top">?</div><div class="dice-state">굴릴 준비 완료</div>`; board.appendChild(card);}}
  function finish(results){const high=Math.max(...results); [...board.children].forEach((card,i)=>{const v=results[i],cube=card.querySelector('.die-cube'),top=card.querySelector('.dice-result-top'),state=card.querySelector('.dice-state'); cube.classList.remove('dice-rolling'); cube.classList.add('dice-final'); cube.style.setProperty('--final-transform',finalRotation[v]); top.textContent=v; top.classList.add('result-pop'); state.textContent=v===high?'최고 숫자!':'결과 확인'; if(v===high) card.classList.add('is-winner');}); const wins=results.map((v,i)=>v===high?`플레이어 ${i+1}`:'').filter(Boolean).join(', '); summary.textContent=`최고 결과 ${high} · ${wins}`; summary.classList.add('summary-show'); button.disabled=false; button.textContent='🎲 다시 굴리기';}
  function roll(){const count=Math.min(10,Math.max(2,Number(countEl.value)||2)); const results=Array.from({length:count},rand); button.disabled=true; button.textContent='주사위 굴리는 중…'; summary.textContent='주사위가 굴러가고 있습니다…'; summary.classList.remove('summary-show'); renderBoard(count); [...board.children].forEach((card,i)=>{card.classList.add('is-rolling'); const cube=card.querySelector('.die-cube'); cube.style.setProperty('--spinX',`${720+i*37+Math.random()*180}deg`); cube.style.setProperty('--spinY',`${1080+i*71+Math.random()*240}deg`); cube.style.setProperty('--spinZ',`${480+Math.random()*220}deg`);}); setTimeout(()=>finish(results),1650);}
  button.addEventListener('click',roll); countEl.addEventListener('change',()=>renderBoard(Number(countEl.value)||2)); renderBoard(Number(countEl.value)||2);
})();