(function(){
 const minEl=document.getElementById('min'),maxEl=document.getElementById('max'),sticksEl=document.getElementById('stickCount'),drawCountEl=document.getElementById('drawCount'),createBtn=document.getElementById('createSticks'),resetBtn=document.getElementById('resetSticks'),board=document.getElementById('stickBoard'),result=document.getElementById('numberResult'),message=document.getElementById('numberMessage'),customEl=document.getElementById('customItems'); const tabs=[...document.querySelectorAll('.mode-tab')]; if(!createBtn||!board||!customEl)return;
 let mode='range',values=[],picked=new Set(),drawTarget=1,drawn=[];
 const rand=(a,b)=>Math.floor(Math.random()*(b-a+1))+a; const shuffle=a=>{for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}; const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function setMode(m){mode=m;tabs.forEach(t=>t.classList.toggle('active',t.dataset.mode===m));document.querySelectorAll('.range-only').forEach(e=>e.hidden=m!=='range');document.querySelector('.custom-only').hidden=m!=='custom';}
 tabs.forEach(t=>t.addEventListener('click',()=>setMode(t.dataset.mode)));
 function getValues(){if(mode==='custom'){const items=customEl.value.split(/\n/).map(x=>x.trim()).filter(Boolean); if(items.length<2)return null; return shuffle(items.slice()).slice(0,16);} let min=Number(minEl.value),max=Number(maxEl.value),count=Math.min(16,Math.max(2,Number(sticksEl.value)||8)); if(!Number.isFinite(min))min=1;if(!Number.isFinite(max))max=100;if(min>max)[min,max]=[max,min];return Array.from({length:count},()=>String(rand(min,max)));}
 function make(){const src=getValues();if(!src){message.textContent='직접 입력 모드에서는 2개 이상의 항목을 입력해 주세요.';return;} values=shuffle(src.slice()); picked=new Set(); drawn=[]; drawTarget=Math.min(values.length,Math.max(1,Number(drawCountEl.value)||1)); result.textContent='-'; result.className='result-value'; document.getElementById('drawResults').innerHTML=''; message.textContent=`총 ${drawTarget}개를 뽑을 수 있습니다. 원하는 제비부터 골라보세요.`; board.innerHTML=''; values.forEach((v,i)=>{const stick=document.createElement('button');stick.type='button';stick.className='lottery-stick';stick.style.setProperty('--tilt',`${(Math.random()*8-4).toFixed(2)}deg`);stick.style.setProperty('--delay',`${i*35}ms`);stick.innerHTML=`<span class="stick-top"></span><span class="stick-label">?</span><span class="stick-number">${esc(v)}</span>`;stick.addEventListener('click',()=>pick(i,stick));board.appendChild(stick);});}
 function pick(i,stick){if(picked.has(i)||drawn.length>=drawTarget)return;picked.add(i);stick.disabled=true;stick.classList.add('is-picked'); setTimeout(()=>{const value=values[i];drawn.push(value);result.textContent=value;result.className='result-value result-pop';message.textContent=drawn.length<drawTarget?`${drawn.length}번째 결과입니다. ${drawTarget-drawn.length}개 더 뽑을 수 있어요.`:'설정한 뽑기 횟수를 모두 완료했습니다.';document.getElementById('drawResults').innerHTML=drawn.map((v,n)=>`<span><b>${n+1}</b> ${esc(v)}</span>`).join('');if(drawn.length>=drawTarget){[...board.children].forEach((b,j)=>{if(!picked.has(j))b.disabled=true;});}} ,560);}
 createBtn.addEventListener('click',make); resetBtn&&resetBtn.addEventListener('click',make); setMode('range'); make();
})();